name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"

      - name: Instalar dependencias
        run: flutter pub get

      - name: Crear archivo .env (solo para Actions)
        run: |
          mkdir -p assets/config
          echo "API_URL=${{ secrets.API_URL }}" > assets/config/.env

      - name: Compilar APK
        run: flutter build apk --release

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: SmokeAndGrill-APK
          path: build/app/outputs/flutter-apk/app-release.apk
